namespace App.Scripts.GameCommon
{
    public enum Word
    {
        None,
        Hungry,
        Tasteless,
        Unnecessary,
        Sports,
        Hahaha,
        Normal,
        This,
        Food,
        Moo,
        Language,
        Toilet,
        GiveYou,
        No,
        Poo,
        What,
        ThankYou,
        Tired,
        CanFly,
        WannaKnow,
        Delicious,
        DontLike,
        Telephone,
        Sleepy,
        Yeah,
        Yes,
    }
}